---
abstract: 'common tests to check syntax of your modules'
author:
  - 'Jerome Quelin'
build_requires:
  Cwd: 0
  Dist::Zilla::Tester: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-Compile
provides:
  Dist::Zilla::Plugin::CompileTests:
    file: lib/Dist/Zilla/Plugin/CompileTests.pm
    version: 2.003
  Dist::Zilla::Plugin::Test::Compile:
    file: lib/Dist/Zilla/Plugin/Test/Compile.pm
    version: 2.003
recommends:
  Test::Script: 1.05
requires:
  Data::Section: 0
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileGatherer: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  namespace::autoclean: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  MailingList: http://www.listbox.com/subscribe/?list_id=139292
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Test-Compile
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Test-Compile/
  repository: git://github.com/karenetheridge/dist-zilla-plugin-test-compile.git
version: 2.003
x_Dist_Zilla:
  perl:
    version: 5.019001
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::JQUELIN/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::JQUELIN/GatherDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Author::JQUELIN/Test::Compile'
      version: 2.002
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::JQUELIN/PodCoverageTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::JQUELIN/PodSyntaxTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::JQUELIN/ReportVersions::Tiny'
      version: 1.08
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::JQUELIN/PruneCruft'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::JQUELIN/PruneFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::JQUELIN/ManifestSkip'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::JQUELIN/AutoPrereqs'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::JQUELIN/ExtraTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::JQUELIN/NextRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::JQUELIN/PkgVersion'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::JQUELIN/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Author::JQUELIN/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::JQUELIN/ExecDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::JQUELIN/ShareDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Author::JQUELIN/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Author::JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::JQUELIN/Repository'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::JQUELIN/MetaProvides::Package'
      version: 1.14000002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::JQUELIN/MetaConfig'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::HelpWanted
      name: '@Author::JQUELIN/HelpWanted'
      version: 0.2.1
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::JQUELIN/License'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Covenant
      name: '@Author::JQUELIN/Covenant'
      version: 0.1.0
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::JQUELIN/MetaYAML'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::JQUELIN/MetaJSON'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::JQUELIN/ModuleBuild'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::JQUELIN/Readme'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::JQUELIN/ReadmeAnyFromPod'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::JQUELIN/Manifest'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Author::JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::JQUELIN/TestRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::JQUELIN/Git::Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::JQUELIN/Git::Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::JQUELIN/Git::Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::JQUELIN/Git::Push'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::JQUELIN/UploadToCPAN'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: Test::EOL
      version: 0.07
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: DevelopRequires
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300035
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 1
    version: 4.300035
x_author_pledge:
  version: 1
