---
abstract: 'common tests to check syntax of your modules'
author:
  - 'Jerome Quelin'
build_requires:
  Capture::Tiny: 0
  Cwd: 0
  Dist::Zilla::Tester: 0
  Path::Class: 0
  Test::CheckDeps: 0.006
  Test::More: 0.94
  blib: 0
configure_requires:
  Dist::CheckConflicts: 0.02
  Module::Build::Tiny: 0.025
conflicts:
  Test::Kwalitee::Extra: '<= v0.0.8'
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-Compile
provides:
  Dist::Zilla::Plugin::CompileTests:
    file: lib/Dist/Zilla/Plugin/CompileTests.pm
    version: 2.014
  Dist::Zilla::Plugin::Test::Compile:
    file: lib/Dist/Zilla/Plugin/Test/Compile.pm
    version: 2.014
requires:
  Data::Section: 0
  Dist::CheckConflicts: 0.02
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::FileFinderUser: 0
  Dist::Zilla::Role::FileGatherer: 0
  Dist::Zilla::Role::PrereqSource: 0
  Dist::Zilla::Role::TextTemplate: 0
  File::Spec: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  namespace::autoclean: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  MailingList: http://www.listbox.com/subscribe/?list_id=139292
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Test-Compile
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Test-Compile/
  repository: git://github.com/karenetheridge/dist-zilla-plugin-test-compile.git
version: 2.014
x_Dist_Zilla:
  perl:
    version: 5.019002
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Filter/Git::NextVersion'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Filter/Test::Compile'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Filter/PruneFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101642
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Filter/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Filter/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.14000003
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::HelpWanted
      name: '@Filter/HelpWanted'
      version: 0.2.1
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Covenant
      name: '@Filter/Covenant'
      version: 0.1.0
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Filter/ReadmeAnyFromPod'
      version: 0.131500
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Filter/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Git::Check'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/Git::Commit'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/Git::Tag'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/Git::Push'
      version: 2.014
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::ModuleBuildTiny
      name: ModuleBuildTiny
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: configure
          type: requires
      name: ConfigureRequires
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Conflicts
      name: Conflicts
      version: 0.10
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: conflicts
      name: DevelopConflicts
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: conflicts
      name: RuntimeConflicts
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: Test::CheckDeps
      version: 0.007
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: Test::EOL
      version: 0.07
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: ContributorsFromGit
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      name: Git::CheckFor::MergeConflicts
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: Git::CheckFor::CorrectBranch
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: Git::Remote::Check
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.008
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300035
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300035
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300035
x_author_pledge:
  version: 1
x_breaks:
  Test::Kwalitee::Extra: v0.0.8
x_contributors:
  - 'Ahmad M. Zawawi <azawawi@ubuntu.(none)>'
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
  - 'Harley Pig <harleypig@gmail.com>'
  - 'Jerome Quelin <jquelin@gmail.com>'
  - 'Jesse Luehrs <doy@tozt.net>'
  - 'Karen Etheridge <ether@cpan.org>'
  - 'Kent Fredric <kentfredric@gmail.com>'
  - 'Marcel Gruenauer <hanekomu@gmail.com>'
  - 'Olivier Mengué <dolmen@cpan.org>'
  - 'Randy Stauner <randy@magnificent-tears.com>'
  - 'Ricardo SIGNES <rjbs@cpan.org>'
  - 'fayland <fayland@gmail.com>'
